version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tienda-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - vol_postgres_tienda:/var/lib/postgresql/data
      - ./init-db/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    networks:
      - tienda-net

  mongodb:
    image: mongo:6
    container_name: tienda-mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - vol_mongo_tienda:/data/db
    networks:
      - tienda-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tienda-rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - tienda-net

  redis:
    image: redis:7.2
    container_name: tienda-redis
    restart: unless-stopped
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - vol_redis_tienda:/data
    networks:
      - tienda-net

networks:
  tienda-net:
    driver: bridge

volumes:
  vol_postgres_tienda:
  vol_mongo_tienda:
  vol_redis_tienda:
